#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

if [ -n "$1" ]
then
# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "Resource: $RESOURCE_TYPE | Namespace: $NAMESPACE | Name: $NAME | CPU: $CPU | Memory: $MEMORY"
done
else
echo -e "You must provide two variables
        Usage:
         kubeplugin [resourse_type] [namespace]"
fi
