---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container1
        image: nginx
        ports:
        - containerPort: 80
      - name: container2
        image: redis
        ports:
        - containerPort: 6379