---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job
              image: php:7.2-cli
              command: ["php", "bin/console"]
          restartPolicy: OnFailure
  concurrencyPolicy: Allow